<h1 align ="Center"> Exceptions Handling </h1>

An exception is a problem that arises during the execution of a program. When an Exception occurs the normal flow of the program is disrupted and the program/ terminates abnormally, therefore these exceptions are to be handled.

Some of these exceptions are caused by user error, others by programmer error, and others by physical resources that have failed in some manner.

There are mainly three categories of Exceptions in java

+ **Checked exceptions**<br />

A checked exception is an exception that is notified by the compiler at compilation-time, These exceptions cannot simply be ignored, the programmer should handle these exceptions.

Eg: 
```java
import java.io.File;
import java.io.FileReader;

public class FilenotFound_Demo {

   public static void main(String args[]) {		
      File file = new File("E://file.txt");
      FileReader fr = new FileReader(file); 
   }
}
```
In the above example, if the specified file in the constructor doesn't exist,then a FileNotFoundException occurs and the compiler prompts the programmer to handle the exception.

+ **Unchecked exceptions**<br />

An unchecked exception is an exception that occurs at the time of execution. These include programming bugs, such as logic errors or improper use of an API. Runtime exceptions are ignored at the time of compilation.

Eg: 
```java
public class Unchecked_Demo {
   
   public static void main(String args[]) {
      int num[] = {1, 2, 3, 4};
      System.out.println(num[5]);
   }
}
```

In the above example, if a stack overflow occurs, an error will arise and these are not exceptions , but problems that arise beyond the control of the user or the programmer. Errors are typically ignored in our code because we can rarely do anything about an error. 

+ **Errors**<br />

All exception classes are subtypes of the java.lang.Exception class. The exception class is a subclass of the Throwable class. Other than the exception class there is another subclass called Error which is derived from the Throwable class.

Errors are abnormal conditions that happen in case of severe failures, these are not handled by the Java programs. Errors are generated to indicate errors generated by the runtime environment. Example: JVM is out of memory. Normally, programs cannot recover from errors.

### Exceptions Methods

|	Exception	|	Description	|
|	--------------------------------------------------------------------	|	--------------------------------------------------------------------	|
|	**public String getMessage()**	|	Returns a detailed message about the exception that has occurred. <br /> This message is initialized in the Throwable constructor.	|
|	**public Throwable getCause()**	|	Returns the cause of the exception as represented by a Throwable object.	|
|	**public String toString()**	|	Returns the name of the class concatenated with the result of getMessage().	|
|	**public void printStackTrace()**	|	Prints the result of toString() along with the stack trace to System.err, the error output stream.	|
|	**public StackTraceElement [] getStackTrace()**	|	Returns an array containing each element on the stack trace. <br > The element at index 0 represents the top of the call stack, <br /> and the last element in the array represents the method at the bottom of the call stack.	|
|	**public Throwable fillInStackTrace()**	|	Fills the stack trace of this Throwable object with the current stack trace, <br /> adding to any previous information in the stack trace.	|

#### Catching Exceptions

+ **Try...catch** <br />

A method catches an exception using a combination of the try and catch keywords. A try/catch block is placed around the code that might generate an exception. 

The **try** statement allows to define a block of code to be tested for errors while it is being executed.

The **catch** statement allows to define a block of code to be executed, if an error occurs in the try block.

Syntax :
```java
try {
   // Protected code
} catch (ExceptionName e1) {
   // Catch block
}
```

Eg:
```java
import java.io.*;

public class ExcepTest {

   public static void main(String args[]) {
      try {
         int a[] = new int[2];
         System.out.println("Access element three :" + a[3]);
      } catch (ArrayIndexOutOfBoundsException e) {
         System.out.println("Exception thrown  :" + e);
      }
      System.out.println("Out of the block");
   }
}
```

+ **Multiple Catch Blocks**

A try block can be followed by multiple catch blocks.

Syntax:
```java
try {
   // Protected code
} catch (ExceptionType1 e1) {
   // Catch block
} catch (ExceptionType2 e2) {
   // Catch block
} catch (ExceptionType3 e3) {
   // Catch block
}
```

Eg:
```java
try {
   file = new FileInputStream(fileName);
   x = (byte) file.read();
} catch (IOException i) {
   i.printStackTrace();
   return -1;
} catch (FileNotFoundException f) // Not valid! {
   f.printStackTrace();
   return -1;
}
```

+ **The Finally Block**

The finally block follows a try block or a catch block. A finally block of code always executes, irrespective of occurrence of an Exception.

Syntax:
```java
try {
   // Protected code
} catch (ExceptionType1 e1) {
   // Catch block
} catch (ExceptionType2 e2) {
   // Catch block
} catch (ExceptionType3 e3) {
   // Catch block
}finally {
   // The finally block always executes.
}
```

Eg:
```java
public class ExcepTest {

   public static void main(String args[]) {
      int a[] = new int[2];
      try {
         System.out.println("Access element three :" + a[3]);
      } catch (ArrayIndexOutOfBoundsException e) {
         System.out.println("Exception thrown  :" + e);
      }finally {
         a[0] = 6;
         System.out.println("First element value: " + a[0]);
         System.out.println("The finally statement is executed");
      }
   }
}
```
In the above example, it will execute and print statement in finally block irrespective of whether the exception will get or not.

+ **The Throw/Throws keyword**

If a method does not handle a checked exception, the method must declare it using the throws keyword. The throws keyword appears at the end of a method's signature.

We can throw an exception, either a newly instantiated one or an exception that wejust caught, by using the throw keyword.

**throws** is used to postpone the handling of a checked exception and **throw** is used to invoke an exception explicitly.

Eg:
```java
import java.io.*;
public class className {

   public void deposit(double amount) throws RemoteException {
      // Method implementation
      throw new RemoteException();
   }
   // Remainder of class definition
}
```
A method can declare that it throws more than one exception, in which case the exceptions are declared in a list separated by commas.

Eg: 
```java
import java.io.*;
public class className {

   public void withdraw(double amount) throws RemoteException, 
      InsufficientFundsException {
      // Method implementation
   }
   // Remainder of class definition
}
```

+ **User-defined Exceptions**

We can create customized exception for our operational requirement, we must Keep the following points in mind when writing our own exception
classes

1. All exceptions must be a child of Throwable. <br />
2. If we want to write a checked exception that is automatically enforced by the Handle or Declare Rule, we need to extend the Exception class.
3. If we want to write a runtime exception, we need to extend the RuntimeException class.

Eg: 
```java
import java.io.*;

public class CheckingAccount {
   private double balance;
   private int number;
   
   public CheckingAccount(int number) {
      this.number = number;
   }
   
   public void deposit(double amount) {
      balance += amount;
   }
   
   public void withdraw(double amount) throws InsufficientFundsException {
      if(amount <= balance) {
         balance -= amount;
      }else {
         double needs = amount - balance;
         throw new InsufficientFundsException(needs);
      }
   }
   
   public double getBalance() {
      return balance;
   }
   
   public int getNumber() {
      return number;
   }
}
```
In the above example demonstrates using user-defined exception, the CheckingAccount class contains a withdraw() method that throws an InsufficientFundsException.



